### PR TITLE
Use Godep for skydns

### LINKED ISSUE #122: Use Godep
It looks like a lot of your latest builds have been failing due to upstream changes.

I was wondering if you would care to use Godep to handle pinning dependencies in skydns. Id be willing to add the dependencies even, but right now I'm not sure if skydns is failing because of changes you made, or an upstream package did, or if configuration is wrong.

Going to the last 'stable' tag 2.0.1a, doesn't work because it wont build due to influx. Godep could handle these issues.

### PR DESCRIPTION
**Pull request by ecnahc515**
Adds Godep dependencies to the repo, and updates instructions/dockerfile for
using godep.

Also, everything is currently pinned to the latest of each package, except for
coreos/go-etcd. They released v2.0.0 client bindings recently, which broke
skydns communicating with etcd while in a docker container while I was testing.

Should probably investigate what needs to be done to use the new etcd client
code.

closes #122

### CODE REVIEW

**Comment by ecnahc515** [comment]
Another note: We can run `godep save -r`, and that would re-write all imports to just use the `Godeps/_workspace` directory, so that would eliminate the use of `godep` commands. But then imports are kinda ugly.

**Comment by ecnahc515** [comment]
Seems that travis isn't using godep. Might be due to the Godeps not existing prior to this PR. Also, the 1.3 build is failing, but I have no idea why. Seems most builds have failed recently.

**Comment by miekg** [comment]
omg, what is this ugly (not a personal comment, looking at godep).

We ripping out kubernetes support so that does not need to be added.
Do we need to `Godep` directory or can this be something I don't need to see, like `.godep`?

**Comment by miekg** [comment]
also https://github.com/skynetservices/skydns/issues/124 filed.

**Comment by ecnahc515** [comment]
It's not very customizable. Most tooling expects it to exist like this. The other option, is to *not* include the `_workspace` directory, but that isn't recommended I believe. If we didn't have kubernetes in here, it would severely cut the size of the dependencies.

**Comment by ecnahc515** [comment]
Another reason it's nice to leave it in the `Godep` directory is things like travis automatically notice it uses Godeps, and modifies the GOPATH to use those dependencies.

**Comment by bketelsen** [comment]
I agree godeps is a *Good Thing*.  I use it on all my larger projects.  We don't have a lot of external dependencies in skydns, but it does guarantee that skydns will always build as we expect.

**Comment by ecnahc515** [comment]
Is this potentially happening, or ..?
@miekg

**Comment by miekg** [comment]
No, I'm nacking for now. I still can't get over the repo pollution this adds. And failure to compile with latest Etcd is something I care about.

**Pull request closed without merging**
