### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by rramkumar1**
Fix a typo and add a stub implementation for FirstBackend of this HasSynced() function.

### CODE REVIEW

**Comment by khimaros** [comment]
This change appears to have broken builds:

$ go install -v --tags=purego github.com/skynetservices/skydns
[...]
src/github.com/skynetservices/skydns/server/server.go:147:38: server.backend undefined (type server has no method backend)

**Comment by miekg** [comment]
I'm inclined to rollback all three PRs and then we can try again.

On 12 Jan 2018 20:16, "khimaros" <notifications@github.com> wrote:

This change appears to have broken builds:

$ go install -v --tags=purego github.com/skynetservices/skydns
[...]
src/github.com/skynetservices/skydns/server/server.go:147:38:
server.backend undefined (type server has no method backend)

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/skynetservices/skydns/pull/328#issuecomment-357330974>,
or mute the thread

**Comment by miekg** [comment]
So reverted... but as I said in that PR; you're on you're own with this repo. Soon I will unsubscribe and not care at all about the code here. The path forward is called CoreDNS

**Pull request merged**
