### PR TITLE
add support for etcd basic auth

### LINKED ISSUE #228: support for etcd authentication
any plans for support this feature:
https://github.com/coreos/etcd/blob/master/Documentation/authentication.md

### PR DESCRIPTION
**Pull request by AdoHe**
Fix #228. I think skydns has already support etcd auth, what we want is support etcd basic auth(username&password), am I right? If so I will open a new PR to implement this, this PR rewrite etcd client construction logical.

### CODE REVIEW

**Comment by DerekTBrown** [comment]
How does this enable username and password authentication?

**Comment by AdoHe** [comment]
@DerekTBrown I guess you want to enable basic auth, I will open a PR to enable this.

**Comment by miekg** [comment]
Is this a prerequisite for auth?

**Comment by AdoHe** [comment]
@miekg not a prerequisite for auth, but I do hope we can merge this, I want to make this much more clear.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skynetservices/skydns] add sup..." ]
>@miekg not a prerequisite for auth, but I do hope we can merge this, I want to make this much more clear.

So? Uhm. Should this not have a different subject line? I.e. why do you want
this to be merged? Clearer code?

**Comment by AdoHe** [comment]
@miekg I think for the first commit, I try to rewrite the auth logical to make clearer code. For the second commit, just add the basic auth implementation.

**Comment by AdoHe** [comment]
@DerekTBrown ptal.

**Comment by miekg** [comment]
Looks good. Can you update the README as well? And is it possible to test this in the travis setup?

**Comment by AdoHe** [comment]
Sure, I will update the README. I am not sure whether the travis has covered this, I will check this.

**Comment by AdoHe** [comment]
@miekg the travis ci failed, would you mind checking this? I am afraid travis is using un-secured etcd backend now, you can check [here](https://github.com/skynetservices/skydns/blob/master/server/server_test.go#L58).

**Comment by miekg** [comment]
Of the top of my head: you are working on an older branch. I've fixed the
Travis failure only yesterday. But I will check to confirm.

**Comment by AdoHe** [comment]
@miekg travis just passed, thanks anymore.

**Comment by DerekTBrown** [comment]
+1

**Comment by AdoHe** [comment]
@miekg the test just passed, anything block this pr now?

**Comment by miekg** [comment]
Nothing looks good. I'm not near a computer now

**Pull request merged**
