### PR TITLE
Escape underscore so they wont' turn into hidden nodes in Etcd

### PR DESCRIPTION
**Pull request by miekg**
This PR takes PR #145 and add documentation and more tests.

### CODE REVIEW

**Comment by SpComb** [comment]
Tested the new \_ naming scheme in my environment, and it behaves as expected:

	$ etcdctl ls --recursive -p /skydns/local/skydns
	/skydns/local/skydns/\_tcp/
	/skydns/local/skydns/\_tcp/\_http/
	/skydns/local/skydns/\_tcp/\_http/web1
	/skydns/local/skydns/\_tcp/\_http/web2
	/skydns/local/skydns/web/
	/skydns/local/skydns/web/web1
	/skydns/local/skydns/web/web2

	$ dig +noall +answer +additional @localhost -p 1053 _http._tcp.skydns.local SRV
	_http._tcp.skydns.local. 10     IN      SRV     10 50 80 web2.web.skydns.local.
	_http._tcp.skydns.local. 10     IN      SRV     10 50 80 web1.web.skydns.local.
	$ dig +noall +answer +additional @localhost -p 1053 web1.web.skydns.local A
	web1.web.skydns.local.  10      IN      A       10.0.0.1
	$ dig +noall +answer +additional @localhost -p 1053 web2.web.skydns.local A
	web2.web.skydns.local.  10      IN      A       10.0.0.2

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] Escape underscore so t..." ]
>Tested the new \_ naming scheme in my environment, and it behaves as expected:
>
>	$ etcdctl ls --recursive -p /skydns/local/skydns
>	/skydns/local/skydns/\_tcp/
>	/skydns/local/skydns/\_tcp/\_http/
>	/skydns/local/skydns/\_tcp/\_http/web1
>	/skydns/local/skydns/\_tcp/\_http/web2
>	/skydns/local/skydns/web/
>	/skydns/local/skydns/web/web1
>	/skydns/local/skydns/web/web2
>
>	$ dig +noall +answer +additional @localhost -p 1053 _http._tcp.skydns.local SRV
>	_http._tcp.skydns.local. 10     IN      SRV     10 50 80 web2.web.skydns.local.
>	_http._tcp.skydns.local. 10     IN      SRV     10 50 80 web1.web.skydns.local.
>	$ dig +noall +answer +additional @localhost -p 1053 web1.web.skydns.local A
>	web1.web.skydns.local.  10      IN      A       10.0.0.1
>	$ dig +noall +answer +additional @localhost -p 1053 web2.web.skydns.local A
>	web2.web.skydns.local.  10      IN      A       10.0.0.2

Cool! And thank you.

/Miek

--
Miek Gieben

**Comment by thockin** [comment]
Sadly, I just figured out how to get what I want out of the existing behavior - this will disrupt me.  Don't let that stop you, I guess, but do expect more questions and bug reports.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] Escape underscore so t..." ]
>Sadly, I just figured out how to get what I want out of the existing behavior - this will disrupt me.  Don't let that stop you, I guess, but do expect more questions and bug reports.

I'm fine with holding this off, the less complexity the better.

**Comment by thockin** [comment]
Maybe you should just document that it works this way on purpose and that
all backends are expected to not recurse across leading _ :)

The result I get when I enable the escaping has me very puzzled how to get
the result I want.

**Comment by miekg** [comment]
The changes the current semantics of SkyDNS + Etcd. For now: don't merge.

**Pull request closed without merging**
